# Generated by Django 5.0.1 on 2024-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('dob', models.CharField(max_length=25)),
                ('photo', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=25)),
                ('payment', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='python_register',
        ),
    ]
