# Generated by Django 5.0.1 on 2024-06-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0002_course_register_delete_python_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_register',
            name='payment',
        ),
    ]
