# Generated by Django 5.0.1 on 2024-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0004_course_register_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_register',
            name='course',
            field=models.CharField(max_length=25),
        ),
    ]
