# Generated by Django 5.0.1 on 2024-06-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0011_user_log_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
