# Generated by Django 5.0.1 on 2024-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0012_alter_user_log_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_log',
            old_name='full_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_log',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_log',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_log',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user_log',
            name='qualification',
        ),
    ]
