# Generated by Django 5.0.1 on 2024-06-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0013_rename_full_name_user_log_user_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='net_book',
            new_name='DM_book',
        ),
        migrations.RenameModel(
            old_name='html_book',
            new_name='mernstack_book',
        ),
    ]
