# Generated by Django 5.0.1 on 2024-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0014_rename_net_book_dm_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
