# Generated by Django 5.0.1 on 2024-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0016_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='date',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
