# Generated by Django 5.0.1 on 2024-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0018_alter_trial_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='flutter_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('dob', models.CharField(max_length=25)),
                ('photo', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=25)),
                ('payid', models.CharField(max_length=25)),
            ],
        ),
    ]
