# Generated by Django 5.0.1 on 2024-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0020_class_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('sslc', models.FileField(upload_to='')),
                ('plustwo', models.FileField(upload_to='')),
                ('degree', models.FileField(upload_to='')),
            ],
        ),
    ]
