# Generated by Django 5.0.1 on 2024-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0023_admin_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('pasw', models.CharField(max_length=25)),
            ],
        ),
    ]
