# Generated by Django 5.0.1 on 2024-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0024_current_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_login',
            name='pasw',
        ),
        migrations.AddField(
            model_name='user_log',
            name='photo',
            field=models.FileField(default='pending', upload_to=''),
        ),
    ]
