# Generated by Django 5.0.1 on 2024-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0025_remove_current_login_pasw_user_log_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
