# Generated by Django 5.0.1 on 2024-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0026_alter_user_log_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
