# Generated by Django 5.0.1 on 2024-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0027_user_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_log',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
