# Generated by Django 5.0.1 on 2024-06-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0028_tutor_log_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_link',
            name='link',
        ),
    ]
