# Generated by Django 5.0.1 on 2024-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0029_remove_class_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_link',
            name='topic',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
