# Generated by Django 5.0.1 on 2024-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0030_class_link_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_link',
            name='topic',
            field=models.CharField(max_length=25),
        ),
    ]
