# Generated by Django 5.0.1 on 2024-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0032_apply_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
            ],
        ),
    ]
