# Generated by Django 5.0.1 on 2024-06-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educationapp', '0033_interview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interview',
            new_name='interviewsave',
        ),
    ]
